### PR TITLE
add all user settings

### PR DESCRIPTION
**Pull request by fabiomelen**

### CODE REVIEW

**Comment by daaru00** [comment]
I'm going to merge this in a feature branch to finalize the integration with backoffice settings.

**Comment by daaru00** [comment]
Hi @fabiomelen,

can you provide me a details about the settings value (string, number, boolean, example..) and their default value? 
For example maybe the `language` setting could be a list of supported languages ​​to choose from the backoffice settings panel.

**Comment by fabiomelen** [comment]
yes!

- `language` should be something like `it_it`. It should be equal to site language or user language if the magento site support user language. Ask to @jacopotagliabue for backend values. The `js` just forward that value to the backend
- `groupBy` is a boolean (default true)
- `submitOnSelect` is a boolean (default true). If true is added a callback `function() { this.form.submit(); }`
- `autocompleteOnSelect` should be a long `string`. It is used to provide a custom callback to substitute the predefined callback (submitOnSelect).  Something like `function(suggestion) { // this is input textfield }`
- `autoCompleteMinChars` should be an `int` (default 1). It is the minimum number of characters required to trigger autosuggest
- `autocompleteMaxHeight` should be an `int` (default 300). It is the maximum height of the suggestions container in pixels
- `autocompleteWidth` should be an `string` (default `auto`). It is the suggestions container width in pixels, e.g.: 300, `flex` for max suggestion size and `auto` takes input field width

**Comment by daaru00** [comment]
>autocompleteOnSelect should be a long string. It is used to provide a custom callback to substitute the predefined callback (submitOnSelect). Something like function(suggestion) { // this is input textfield }

>autoCompleteMinChars should be an int (default 1). It is the minimum number of characters required to trigger autosuggest

 If someone want to disable this feature? Maybe is useful to use a select box like:
- `OnSelectBehaviour`: with values `submit`, `nothing`, `custom` 
and when the option is set to `custom` users can insert their own callback logic. What do you think about this?

> `autocompleteWidth` should be an string (default auto). It is the suggestions container width in pixels, e.g.: 300, flex for max suggestion size and auto takes input field width

It is a little bit complicated ask the user to type in the field `flex` and not `felx` (could be contain typo), `auto`, `200px`, it could be understood as a free field and the user maybe will insert `4rem`, `5em`, `40%` and so on.

I think is more easy use two different settings:
- `width`:  select box with values `auto`, `flex`, `custom`
- `customWidth`: `200px`, `300px`... (activated only when the previuos setting is set to `custom`).

I don't know if this parameter allow the possibility to pass every kind of value or there's a check on the value like an if statement.

You miss some parameters:
- `noCache` I think it should be a boolean, it is right?
- `uid` how should it be valorized?

**Comment by fabiomelen** [comment]
- `OnSelectBehaviour` great!.
- `autocompleteWidth` perfect!
-  `noCache` boolean (default false). For now I think that will be false without the ability to admin this value. But put it in place but do not show it to the user.
- `uid` is the same value that you already send to tooso analytics. It should be the `userId`. This should be into the admin console. The `suggest js` asks to `ta.js` if uid is not defined. The `uid` is necessary if the `ta.js` (tooso analytics) is not in the scope of the project.

**Comment by daaru00** [comment]
>The suggest js asks to ta.js if uid is not defined. The uid is necessary if the ta.js (tooso analytics) is not in the scope of the project.

Aaah ok, I get it :+1: 

I think now the merge is completed. I going to deploy into our test environment for the final tests.

Thanks!

**Comment by fabiomelen** [comment]
Could you write me in private the url of the test environment so I can check the`javascritpt`. Please use fabio.melen@gmail.com or skype/fb messenger as fabiomelen.

**Pull request merged**
